apiVersion: app.azure.microsoft.com/v1
kind: Sample
metadata:
  labels:
    app.kubernetes.io/name: example-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample1
  namespace: monitoring
spec:
  foo: "hello"
  bar: 1
